### ISSUE TITLE
warning about nendo_plugin_embed_clap not being loaded when doing analysis through front end

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#12]
I've successfully installed the clap plugin via: 
pip install nendo-plugin-embed-clap

but when I run analysis I get this warning:

19:37:18 085df796-cb6b-4251-9d17-758c720114e5-gpu: Music Analysis (Music_Analysis_7OrhVgDR)
[2024-02-22T19:37:19.256Z] nendo         WARNING Plugin with name nendo_plugin_embed_clap has been configured for the NendoLibraryVectorExtension but is not loaded. Please make sure to install and enable the plugin to use the embedding features of the nendo library.

But I do see a caption in the resulting metadata. Is the caption generated via CLAP?

**Comment by jhurlbut** [comment]
It seems that nando-platform is not configured for the latest version of the embedding plugin by default

**Comment by faradox** [comment]
Most likely, you see this warning in the Nendo API Server's logs. There, it can be safely ignored as the server does not embed tracks itself and thus the `nendo_plugin_embed_clap` plugin is not loaded for optimization purposes. The tools (like musicanalysis) that compute embeddings run in their own docker containers and have the plugin enabled, thus the embeddings are successfully created.

Also, note that CLAP is used for captioning, however not by means of the embedding plugin but of the [captioning plugin](https://github.com/okio-ai/nendo_plugin_caption_lpmusiccaps). Same model under the hood, two different plugins that use it in different ways :)

**Comment by faradox** [comment]
Let me know if you encounter any actual interruptions in relationship to this warning. Otherwise, I'll close this ticket as the warning itself is not an issue

**Comment by jhurlbut** [comment]
Thanks. What's a good way to verify that the embeddings are being computed properly?

**Comment by faradox** [comment]
If you open the context menu of a track and click "show similar", it shows similar tracks only if the track has an embedding. Otherwise you'll see an error asking you to compute the embedding.

**Comment by faradox** [comment]
Will close this thread for now as the issue seems resolved. Let me know if you still encounter problems related to this and I can re-open it.
