### ISSUE TITLE
Can a single 4090 graphic card run this project?

### ISSUE THREAD

**Issue by HildaM** [okio-ai/nendo-platform#2]
I wonder if I can limit the model ability to run on my PC with 4090.

**Comment by faradox** [comment]
The short answer is yes :) A 4090 has 24 GB of VRAM which meets the required minimum for all Nendo tools to run properly.

The more precise answer is that you might need to adjust the base image used for Nendo's tools to fit your version of the NVIDIA drivers. I added [a new section about this to the README](https://github.com/okio-ai/nendo-platform?tab=readme-ov-file#gpu-compatibility) that provides all the necessary information. Let me know if something remains unclear.

Thank you for raising this issue, it made me aware that the README was imprecise about that very important aspect.

Have a nice day!
