### ISSUE TITLE
errors when using the sound generation

### ISSUE THREAD

**Issue by leoleelxh** [okio-ai/nendo-platform#28]
This is a great tool, but I encountered these errors when using the sound generation function. How to solve it?
![image](https://github.com/okio-ai/nendo-platform/assets/4277749/26504e5f-fc62-4a17-a9db-a59fb5dbfa19)

**Comment by aaronabebe** [comment]
Hi @leoleelxh! 

The error message looks like a connection issue that occurred when downloading the voice generation model from Hugging Face. 
When you run the tool for the first time, the models get downloaded and cached in the background. 

Can you make sure that you have a stable internet connection on first run and retry running the tool?

**Comment by faradox** [comment]
Please let us know if this resolved your issue so we can close this thread

**Comment by faradox** [comment]
Closing this thread due to inactivity
