### ISSUE TITLE
unable to run polymath anymore

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#30]
I'm not sure if it's related to pulling the latest but I can no longer run polymath on any of my tracks. I always get errors similar to this:

Action ID: Polymath_I5qXQtwR

Action Target: 5b851e90-22cb-4a66-9e1b-e2cedc4e3357

Action Parameters:
add_to_collection_id:
beats_per_loop: 4
classify: true
embed: true
loopify: true
n_loops: 4
quantize: false
quantize_to_bpm: 120
stem_types: [ "vocals", "drums", "bass", "other" ]
stemify: true
target_id: 5b851e90-22cb-4a66-9e1b-e2cedc4e3357
Action Errors:
Error processing track 5b851e90-22cb-4a66-9e1b-e2cedc4e3357: Error with resource /home/nendo/separated/htdemucs_ft/8b1e99ac-2442-4336-bd3e-782dea2f89eb/vocals.wav. Details: File not found

It looks like it's not saving the stems properly or something?

**Comment by faradox** [comment]
We're aware of the issue and have all hands on fixing it. Meanwhile, can you confirm that it depends on the specific track you run polymath on? Or does it occur regardless of the track?

**Comment by jhurlbut** [comment]
It appears to occur regardless of the track. I am able to run polymath if I only select stems but not stems, loopify, and embeddings. I thought maybe it was related to skip duplicates being enabled thinking that the processed files were incorrectly marked as dupes but after setting that flag to false it still won't work. BTW, Is polymath "Classify" the same process as "Music Analysis"?

**Comment by jhurlbut** [comment]
I ran make update, make build-dev, and make run-dev and then tried running polymath. I got this error:

Action ID: Polymath_zSvcGPV1_0

Action Target: f6f9f7d4-c411-4114-9f08-39306a752c50

Action Parameters:
add_to_collection_id:
beats_per_loop: 4
classify: true
embed: true
loopify: true
n_loops: 4
quantize: false
quantize_to_bpm: 120
stem_types: [ "vocals", "drums", "bass", "other" ]
stemify: true
target_id: a3686740-0190-4bd9-8096-d6f0976cfcf0
Action Errors:
Error processing track f6f9f7d4-c411-4114-9f08-39306a752c50: too many values to unpack (expected 2)
Traceback (most recent call last): File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job rv = job.perform() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform self._result = self._execute() File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute result = self.func(*self.args, **self.kwargs) File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 179, in dockerized_func raise Exception(err_log) Exception: [' results = run_polymath(', ' File "run.py", line 306, in run_polymath', ' for num_loop, lp in stem_loops:', 'ValueError: too many values to unpack (expected 2)', '']

**Comment by faradox** [comment]
I just committed a fix for that problem, please run `make update` and `make run-dev` again and it should work again

**Comment by jhurlbut** [comment]
Cool it works now but I had to re-add my track before it worked again for some reason
