### ISSUE TITLE
Allow adding tracks from youtube directly into the library

### ISSUE THREAD

**Issue by aaronabebe** [okio-ai/nendo-platform#31]
As a Nendo user, I would like to be able to add tracks directly from youtube into the library by specifying a youtube video URL or add a collection directly by specifying a youtube playlist URL.

**Comment by faradox** [comment]
Feature has been  added as https://github.com/okio-ai/nendo-server/commit/0bda898c69797947a51753797dc496e182b65ffa and https://github.com/okio-ai/nendo-web/commit/41a3cfff4e9b3ab6b6e13719998b6b2db2932a10
