### ISSUE TITLE
make flush returns errors if platform not running

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#35]
(nendo) james@techno:~/nendoproject/nendo-platform$ make flush
Are you sure you want to delete all rows from the specified tables? [y/N] y
Error response from daemon: Container 6d1f20442d5fb160fd1576f0ab23358a71e6597ab538cc118f878edc7e4727ce is not running

If I open a new terminal I can make flush but then if I run make run-dev in that new terminal I get this output:

(nendo) james@techno:~/nendoproject/nendo-platform$ make run-dev
Running with HOST_CWD=/home/james/nendoproject/nendo-platform, USE_GPU=
make stop
make[1]: Entering directory '/home/james/nendoproject/nendo-platform'
[+] Running 4/5
 ⠿ Container nendo-gateway   Removed                                       0.4s
 ⠿ Container nendo-web       Error while Removing                         10.4s
 ⠿ Container nendo-server    Removed                                       0.9s
 ⠿ Container nendo-postgres  Removed                                       0.4s
 ⠿ Container nendo-redis     Removed                                       0.4s
Error response from daemon: removal of container baa8e9092b299abdf50c94f443a804f3327f2485e7a008deb5266a7cc034fb72 is already in progress
make[1]: Leaving directory '/home/james/nendoproject/nendo-platform'
Both images found. Running application...
[+] Running 6/5
 ⠿ Network nendo-internal    Created                                       0.1s
 ⠿ Container nendo-web       Created                                       0.0s
 ⠿ Container nendo-redis     Created                                       0.0s
 ⠿ Container nendo-postgres  Created                                       0.0s
 ⠿ Container nendo-server    Created                                       0.1s
 ⠿ Container nendo-gateway   Created                                       0.0s
Attaching to nendo-gateway, nendo-postgres, nendo-redis, nendo-server, nendo-web
nendo-redis     | 1:C 29 Feb 2024 22:49:59.023 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
nendo-redis     | 1:C 29 Feb 2024 22:49:59.023 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
nendo-redis     | 1:C 29 Feb 2024 22:49:59.023 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
nendo-redis     | 1:C 29 Feb 2024 22:49:59.023 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
nendo-redis     | 1:M 29 Feb 2024 22:49:59.024 * monotonic clock: POSIX clock_gettime
nendo-redis     | 1:M 29 Feb 2024 22:49:59.025 * Running mode=standalone, port=6379.
nendo-redis     | 1:M 29 Feb 2024 22:49:59.025 * Server initialized
nendo-redis     | 1:M 29 Feb 2024 22:49:59.026 * Ready to accept connections tcp
nendo-postgres  | 
nendo-postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
nendo-postgres  | 
nendo-postgres  | 2024-02-29 22:49:59.081 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
nendo-postgres  | 2024-02-29 22:49:59.081 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
nendo-postgres  | 2024-02-29 22:49:59.081 UTC [1] LOG:  listening on IPv6 address "::", port 5432
nendo-postgres  | 2024-02-29 22:49:59.082 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
nendo-postgres  | 2024-02-29 22:49:59.086 UTC [29] LOG:  database system was shut down at 2024-02-29 22:49:47 UTC
nendo-postgres  | 2024-02-29 22:49:59.090 UTC [1] LOG:  database system is ready to accept connections

**Comment by faradox** [comment]
`make flush` can only work if Nendo is already running. Upon your hint, I added a check that will make the command fail if that condition is not met, and provide this information to the user. Thanks for the input!

As for you other error, it seems that you are trying to run Nendo twice in two separate shells, which is not supported. If you are running Nendo in development mode and want to flush the library, please spawn two shells. In the first one, run Nendo (`make run-dev`), then, when it is started, run `make flush` in the second shell and you should be good.
