### ISSUE TITLE
Mashuper not working

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#41]
I'm unable to run Mashuper. Heres the error:

06:30:00 [Job Quantize_0D1j1aFi_0]: exception raised while executing (handler.nendo_actions_handler.dockerized_func)
nendo-server | Traceback (most recent call last):
nendo-server | File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job
nendo-server | rv = job.perform()
nendo-server | File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform
nendo-server | self._result = self._execute()
nendo-server | File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute
nendo-server | result = self.func(*self.args, **self.kwargs)
nendo-server | File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 179, in dockerized_func
nendo-server | raise Exception(err_log)
nendo-server | Exception: [' quantize(', ' File "run.py", line 17, in quantize', ' q_track = track.process("nendo_plugin_quantize_core", bpm=target_bpm)', "AttributeError: 'NoneType' object has no attribute 'process'", '']

**Comment by faradox** [comment]
Fixed. Please update Nendo and continue mashup'ing :) Apologies for the inconvenience
