### ISSUE TITLE
Hot reload / rebuild not working on make run-dev

### ISSUE THREAD

**Issue by boringtaskai** [okio-ai/nendo-platform#45]
Hi I tried to run 'make run-dev' and then I modified the code inside the repo/nendo-web/src folder, but the hot reload feature is not working, do you have any idea, to make it works? 

I'm using:
OS: Windows 11 on WSL2 ubuntu 22
Docker: version 24

**Comment by faradox** [comment]
Hi @boringtaskai I assume you also built the development images before as they are needed for running Nendo in development mode?

Use `make build-dev`, then try again `make run-dev` and hot-reloading should be enabled. Let us know if this resolves your issue.

**Comment by boringtaskai** [comment]
Yes I did build-dev to make the nendo-web image,

Oh I think I found the issue, I think the hot reload only monitor file inside repo/nendo-web/src only, not include the files, in the src/ subfolder (eg. components/, router/, views/, stores/. etc)

**Comment by faradox** [comment]
No, the hot-reloading is triggered by all changes in the `src/` directory and all it's sub-directories. Please make sure you are really editing the files in the WSL2 environments `repo/nendo-web/src` directory and not another directory on the windows host. We've tried to reproduce this issue with the specified environment but it's working fine for us. Please provide some more information, like which IDE you are using and where you placed your code in the WSL guest. For example, [in this thread](https://github.com/facebook/create-react-app/issues/10253#issuecomment-940654613), [and this thread](https://github.com/vuejs/vue-cli/issues/4421#issuecomment-557194129) users report that the code has to reside in the ubuntu file system, and not in the Windows FS. Also, if you're using VS Code, you might need [an extension](https://github.com/vuejs/vue-cli/issues/4421#issuecomment-571220408) to be able to live-edit the code in the WSL

**Comment by boringtaskai** [comment]
Hi, 

I think I found the solution, the problem arises because I put repo/nendo-web in the Windows Filesystem, not in the Linux Filesystem, and I found the same problem here [Vite issue](https://github.com/vitejs/vite/issues/1153), and the solution is to add usePolling: true in the  repo/nendo-web/vite.config.js and it works.  I will make PR 

`export default defineConfig({
  server: {
   ...
    watch: {
      usePolling: true,
    },
   ...
  }
})`
