### ISSUE TITLE
Feature: Add development mode for tools

### ISSUE THREAD

**Issue by faradox** [okio-ai/nendo-platform#51]
As a Nendo Platform developer, I want to be able to easily develop new tools and make changes to Nendo core and it's various plugins and test those changes directly in the Nendo Platform. For this, I need the introduction of _development mode_ for the tool images built for the Nendo Platform.

**Comment by jhurlbut** [comment]
I'm getting this error when running setup-dev:

Step 7/8 : COPY dependencies/nendo_plugin_musicgen /home/nendo/nendo_plugin_musicgen
COPY failed: file not found in build context or excluded by .dockerignore: stat dependencies/nendo_plugin_musicgen: file does not exist
make: *** [Makefile:73: build-tools-gpu-dev] Error 1

**Comment by faradox** [comment]
oops, my bad. Just fixed it. Please update and run `make setup-dev` again
