### ISSUE TITLE
Error When uilding build/Dockerfile.polymath after pulling the latest commit #66

### ISSUE THREAD

**Issue by boringtaskai** [okio-ai/nendo-platform#70]
Here is the error message when building build/Dockerfile.polymath

 [dev 12/18] RUN pip install /home/nendo/:
0.987 Defaulting to user installation because normal site-packages is not writeable
1.186 ERROR: Directory '/home/nendo/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

I found the solution, by adding the subfolder nendo in the Dockerfile.polymath file (according to the build/Dockerfile.core)

```
- RUN pip install --ignore-installed /home/nendo/
+ RUN pip install --ignore-installed /home/nendo/nendo
```

**Comment by faradox** [comment]
Commited the fix as https://github.com/okio-ai/nendo-platform/commit/677aecd59e6f65d5fe731992a5507739dbc778cb Thanks for reporting!
