### ISSUE TITLE
MusicGen Trainer error

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#73]
I'm getting the error:

nendo-server    | 06:54:32 [Job MusicGen_training_ZiNmVrYI_0]: exception raised while executing (handler.nendo_actions_handler.dockerized_func)
nendo-server    | Traceback (most recent call last):
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/worker.py", line 1431, in perform_job
nendo-server    |     rv = job.perform()
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1280, in perform
nendo-server    |     self._result = self._execute()
nendo-server    |   File "/home/nendo/.local/lib/python3.8/site-packages/rq/job.py", line 1317, in _execute
nendo-server    |     result = self.func(*self.args, **self.kwargs)
nendo-server    |   File "/home/nendo/nendo-server/nendo_server/./handler/nendo_actions_handler.py", line 203, in dockerized_func
nendo-server    |     raise Exception(err_log)
nendo-server    | Exception: ['    nd.plugins.musicgen.train(', '  File "/home/nendo/.local/lib/python3.8/site-packages/nendo/schema/core.py", line 1888, in __getattr__', '    raise NendoPluginRuntimeError(', 'nendo.schema.exception.NendoPluginRuntimeError: Plugin nendo_plugin_musicgen has no function train', '']

When trying to run MusicGen Trainer. I have run make update, make setup-dev and make build-dev

**Comment by faradox** [comment]
Please try what was suggested in [this thread](https://github.com/okio-ai/nendo-platform/issues/71#issuecomment-2010241243) and let me know if it helps

**Comment by jhurlbut** [comment]
that fixed it. thanks
