### ISSUE TITLE
make command for shutting down web server

### ISSUE THREAD

**Issue by jhurlbut** [okio-ai/nendo-platform#9]
I see that make run will shut down all the nendo services first but I don't see a make command for just shutting down the services. My issue is that I'm unable to run make run-dev after running make run because the web service is stil running. Error is:

failed to remove network nendo-internal: Error response from daemon: error while removing network: network nendo-internal id 27f94f0a50c53145e1dddbd1252715e905b8e5ef730bf2941dedcd950935d1bd has active endpoints
make: *** [Makefile:73: run-dev] Error 1

**Comment by jhurlbut** [comment]
Acutally now I am unable to re-run make run. This is the output

make run
Running with HOST_CWD=/home/james/nendoproject/nendo-platform
Both images found. Running application...
Running insecure mode (no SSL)
[+] Running 4/4
 ⠿ Container nendo-server    Removed                                                                                      1.2s
 ⠿ Container nendo-web       Removed                                                                                      0.4s
 ⠿ Container nendo-redis     Removed                                                                                      0.4s
 ⠿ Container nendo-postgres  Removed                                                                                      0.4s
 ⠿ Network nendo-internal    Error                                                                                        0.0s
failed to remove network nendo-internal: Error response from daemon: error while removing network: network nendo-internal id 27f94f0a50c53145e1dddbd1252715e905b8e5ef730bf2941dedcd950935d1bd has active endpoints
[+] Running 4/4
 ⠿ Container nendo-postgres  Started                                                                                      0.6s
 ⠿ Container nendo-redis     Started                                                                                      0.4s
 ⠿ Container nendo-web       Started                                                                                      0.7s
 ⠿ Container nendo-server    Started

**Comment by faradox** [comment]
Nice catch! I will commit a proper solution to this problem in a bit. For now you can just call:

```bash
HOST_CWD=$(pwd) docker compose --profile prod-http down ; docker container prune
```

And then you can run `make run-dev` again

**Comment by faradox** [comment]
I updated the `Makefile` to fix this issue. Just pull the latest changes from `main` or call `make update-dependencies` which will do that for you. Then, you have the new `make stop` command to stop the app at any time. Also, switching between `make run` and `make run-dev` should be seamless, **however** keep in mind that you should actually build the development version of the images before that by calling `make build-dev` in order to actually have the development mode features.
